repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=5000']
  - id: check-docstring-first
  - id: check-json
    args: [--autofix]
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: pretty-format-json
  - id: trailing-whitespace
  - id: sort-simple-yaml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-java
    args: [--autofix]
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.2
  hooks:
  - id: mdformat
